# Generated by Django 4.2.21 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Краткая биография')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/', verbose_name='Фотография')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
