# Generated by Django 4.2.21 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('goal', models.TextField(verbose_name='Цель проекта')),
                ('result', models.TextField(blank=True, verbose_name='Результаты')),
                ('start_year', models.PositiveSmallIntegerField(default=2024, verbose_name='Начало')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Окончание')),
                ('sponsor', models.CharField(blank=True, max_length=150, verbose_name='Спонсор / заказчик')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Изображение')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
