version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: islab_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: islab_db
      MYSQL_USER: islab_user
      MYSQL_PASSWORD: islab_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: islab_django
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn ISLab.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  tailwind:
    build:
      context: .
    container_name: islab_tailwind
    command: "python manage.py tailwind start"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web

volumes:
  mysql_data:
