# Generated by Django 5.2 on 2025-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Полное описание')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('authors', models.CharField(max_length=300, verbose_name='Авторы')),
                ('journal', models.CharField(max_length=300, verbose_name='Журнал / источник')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на скачивание')),
            ],
        ),
    ]
