# Generated by Django 5.2 on 2025-04-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec_lab_app', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/extra/', verbose_name='Файл изображения')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infosec_lab_app.news', verbose_name='Новость')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
